// This file was generated by Slater.app - 2k

let paths = window.location.pathname.split('/')


// css -> 
{ 
  const link = document.createElement('link'); 
  link.rel = 'stylesheet'; 
  link.href = 'https://slater.app/16118/43384.css?v=274437'; 
  document.head.appendChild(link); 
} 
 

// loader -> 
import('https://slater.app/16118/43416.js?v=501286')


// vtec -> 
import('https://slater.app/16118/43300.js?v=300739')


// parallax -> 
import('https://slater.app/16118/43480.js?v=552637')


